package hello;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.ui.Model;


@Controller    // This means that this class is a Controller

public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    UserRepository userRepository;

    @RequestMapping("/aui")
    public String aui(){
        return "aui";
    }

    @RequestMapping("/sui")
    public String sui(){
        return "sui";
    }


}