package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.ui.Model;


@Controller    // This means that this class is a Controller

public class MyProfileController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data


    @RequestMapping("/myProfile")
    public String myProfile() {

        return "myProfile";
    }

    @RequestMapping("/aui")
    public String aui(){
        return "aui";
    }

}
